server:
  port: 3000
spring:
  application:
    name: showsync
  datasource:
    password:
    url:
    username:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: test
      password: test123
